### ISSUE TITLE
Share a quote from a movie

### ISSUE THREAD

**Issue by SavvasStephanides** [SavvasStephanides/say-something#16]
Share a quote from your favourite movie or a movie you've watched recently!

Use the [guide to submitting your own message](https://just-say-something.vercel.app/write)

**Comment by therefat** [comment]
> Share a quote from your favourite movie or a movie you've watched recently!
> 
> Use the [guide to submitting your own message](https://just-say-something.vercel.app/write)

assign me

**Comment by SavvasStephanides** [comment]
Go for it @therefat

**Comment by therefat** [comment]
done check please
