### ISSUE TITLE
Share an inspirational quote.

### ISSUE THREAD

**Issue by SavvasStephanides** [SavvasStephanides/say-something#30]
Share a quote about anything that you like.

Recommended for people making their first ever open source contribution.

Use the [guide to submitting your own message](https://just-say-something.vercel.app/write)

**Comment by burhanharoon** [comment]
Hi @SavvasStephanides , could you assign this issue to me, I would love to work on it. Thanks.

**Comment by SavvasStephanides** [comment]
All yours @burhanharoon!
