### ISSUE TITLE
Share an inspirational saying in a language that's not English

### ISSUE THREAD

**Issue by SavvasStephanides** [SavvasStephanides/say-something#6]
Share a quote on the Say Something site on a language other than English. Include an English translation. Use the [guide to submitting your own message](https://just-say-something.vercel.app/write)

**Comment by sidxh** [comment]
hey, can I be assigned this task?

**Comment by SavvasStephanides** [comment]
All yours @sidxh 🔥

**Comment by sidxh** [comment]
#19 I have added the quote!
