### ISSUE TITLE
Share a programming joke

### ISSUE THREAD

**Issue by SavvasStephanides** [SavvasStephanides/say-something#7]
Share a programming joke on the Say Something website. It can be anything from a well-known one to your original joke!

Use the [guide to submitting your own message](https://just-say-something.vercel.app/write)

**Comment by WilsonZ-CS** [comment]
Can I be assigned to this task please? Thank you!

**Comment by SavvasStephanides** [comment]
Ask yours, @WilsonZ-CS

**Comment by Sha1kh4** [comment]
@SavvasStephanides  check my pr please.
