### ISSUE TITLE
Share a quote from your favourite book.

### ISSUE THREAD

**Issue by SavvasStephanides** [SavvasStephanides/say-something#8]
Share a line from a book you've read recently and loved. It can be about everything and anything.

Use the [guide to submitting your own message](https://just-say-something.vercel.app/write)

**Comment by RileeyL** [comment]
hi @SavvasStephanides , can I please be assigned to this task? Thanks!

**Comment by SavvasStephanides** [comment]
Go for it, @RileeyL 🔥
